[package]
name = "mandelbrot_renderer"
version = "0.1.0"
authors = ["MSchalk <schalk.moritz@yahoo.de>"]

[dependencies]
sdl2 = "0.31"
num-complex = "0.2"
palette = "0.4.1"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"